/*
389. Find the Difference
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
 */
package Leetcode;

public class _389 {
    public static void main(String[] args) {
        String s1 = "abcd";
        String s2 = "abcde";
        System.out.println(findTheDifference(s1,s2));
    }
    static char findTheDifference(String s, String t){
        long sum1 = 0;
        long sum2 = 0;
        for(int i = 0; i<s.length(); i++){
            sum1 = sum1 + (int)s.charAt(i);
        }
        for(int i = 0; i<t.length(); i++){
            sum2 = sum2 + (int)t.charAt(i);
        }
        sum2 = sum2 -sum1;
        return (char)sum2;

    }
}
